version: '3.9'

services:
  db:
    container_name: url-shortener-db
    image: mysql
    volumes:
      - url-shortener-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'url-shortener-data'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: 'mysqladmin ping --silent'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  url-shortener-data: